DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS catagory;

CREATE TABLE catagory (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
);

CREATE TABLE item (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
);