DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS catagory;
DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS Feature;

CREATE TABLE catagory (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE Item (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE Location (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE Feature (
  id INTEGER AUTO_INCREMENT PRIMARY KEY.
  name VARCHAR(50) NOT NULL,
  detail VARCHAR(50) NOT NULL
);